OUTPUT=modbin_win32.exe

CC    = i686-w64-mingw32-gcc
STRIP = i686-w64-mingw32-strip
CFLAG = -Os -static -I.

SRC   = $(wildcard *.c)
OBJ   = $(SRC:.c=.win32.o)

%.win32.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

all: $(OUTPUT)

$(OUTPUT): $(OBJ)
	$(CC) $(CFLAGS) -o $(OUTPUT) $(OBJ)
	$(STRIP) --strip-all $(OUTPUT)

clean:
	rm -vf $(OUTPUT) $(OBJ)
